version: 0.1
phases:
    pre_build:
        commands:
            - echo RUNNING PRE_BUILD COMMANDS...
            - echo "123" > /tmp/build_id.out
            - printf "kgdockertest:123" > /tmp/build_tag.out
            - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
            - $(aws ecr get-login)
    build:
        commands:
            - docker build --tag "$(cat /tmp/build_tag.out)" .
    post_build:
        commands:
            - docker push "$(cat /tmp/build_tag.out)"
    artifacts:
        files: /tmp/build.json
        discard-paths: yes