version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t kgdockertest .
      - docker tag kgdockertest:latest $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/kgdockertest:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/kgdockertest:latest
